=== baioumyhiba/Projet_bibliotheque/data/users/menus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="menus">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="menu" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="label">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="key" type="xsd:string" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="link" type="xsd:string"/>
              <xsd:element name="icon" type="xsd:string"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="roles" type="xsd:string" use="required"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== baioumyhiba/Projet_bibliotheque/data/users/menus.xml
<?xml version="1.0" encoding="UTF-8"?>
<menus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="menus.xsd">


    <menu id="home" roles="admin user auteur">
        <label key="menu.home">Accueil</label>
        <link>#home</link>
        <icon>🏠</icon>
    </menu>

    <menu id="consultation" roles="admin user auteur">
        <label key="menu.consult">Consultation</label>
        <link>#consultation</link>
        <icon>📚</icon>
    </menu>

    <menu id="manage_books" roles="admin auteur">
        <label key="menu.manage_books">Gestion Livres</label>
        <link>#books</link>
        <icon>📖</icon>
    </menu>

    <menu id="manage_authors" roles="admin">
        <label key="menu.manage_authors">Gestion Auteurs</label>
        <link>#authors</link>
        <icon>✍️</icon>
    </menu>

    <menu id="manage_users" roles="admin">
        <label key="menu.manage_users">Gestion Utilisateurs</label>
        <link>#users</link>
        <icon>👥</icon>
    </menu>

    <menu id="manage_categories" roles="admin">
        <label key="menu.manage_categories">Gestion Catégories</label>
        <link>#categories</link>
        <icon>🏷️</icon>
    </menu>

    <menu id="profile" roles="admin user auteur">
        <label key="menu.profile">Mon Profil</label>
        <link>#profile</link>
        <icon>👤</icon>
    </menu>

    <menu id="logout" roles="admin user auteur">
        <label key="menu.logout">Déconnexion</label>
        <link>#logout</link>
        <icon>🚪</icon>
    </menu>

</menus>
