=== baioumyhiba/Projet_bibliotheque/data/authors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Définition d'une référence de livre -->
    <xs:element name="livreref">
        <xs:complexType>
            <xs:attribute name="idLivre" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Définition de la liste de livres pour un auteur -->
    <xs:element name="livres">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="livre" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Définition d'un auteur -->
    <xs:element name="auteur">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nom" type="xs:string"/>
                <xs:element name="pays" type="xs:string"/>
                <xs:element ref="livres"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Racine : liste des auteurs -->
    <xs:element name="auteurs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="auteur" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== baioumyhiba/Projet_bibliotheque/data/authors.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="authors.xsl"?><auteurs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authors.xsd">

    <!-- Littérature française -->
    

    <auteur id="A2">
        <nom>Gustave Flaubert</nom>
        <pays>France</pays>
        <livres>
            <livreref idLivre="L3"/>
        </livres>
    </auteur>

    <auteur id="A3">
        <nom>Honoré de Balzac</nom>
        <pays>France</pays>
        <livres>
            <livreref idLivre="L4"/>
        </livres>
    </auteur>

    <auteur id="A4">
        <nom>Albert Camus</nom>
        <pays>France</pays>
        <livres>
            <livreref idLivre="L5"/>
        </livres>
    </auteur>

    <!-- Littérature marocaine -->
    <auteur id="A5">
        <nom>Ahmed Sefrioui</nom>
        <pays>Maroc</pays>
        <livres>
            <livreref idLivre="L6"/>
        </livres>
    </auteur>

    <auteur id="A6">
        <nom>Driss Chraïbi</nom>
        <pays>Maroc</pays>
        <livres>
            <livreref idLivre="L7"/>
        </livres>
    </auteur>

    <auteur id="A7">
        <nom>Mohammed Khair-Eddine</nom>
        <pays>Maroc</pays>
        <livres>
            <livreref idLivre="L8"/>
        </livres>
    </auteur>

    <auteur id="A8">
        <nom>Mohamed Choukri</nom>
        <pays>Maroc</pays>
        <livres>
            <livreref idLivre="L9"/>
        </livres>
    </auteur>

    <!-- Littérature mondiale -->
    <auteur id="A9">
        <nom>Miguel de Cervantès</nom>
        <pays>Espagne</pays>
        <livres>
            <livreref idLivre="L10"/>
        </livres>
    </auteur>

    <auteur id="A10">
        <nom>George Orwell</nom>
        <pays>Royaume-Uni</pays>
        <livres>
            <livreref idLivre="L11"/>
        </livres>
    </auteur>

    <auteur id="A11">
        <nom>Antoine de Saint-Exupéry</nom>
        <pays>France</pays>
        <livres>
            <livreref idLivre="L12"/>
        </livres>
    </auteur>

    <auteur id="A12">
        <nom>Fiodor Dostoïevski</nom>
        <pays>Russie</pays>
        <livres>
            <livreref idLivre="L13"/>
        </livres>
    </auteur>

    <auteur id="A13">
        <nom>Jane Austen</nom>
        <pays>Royaume-Uni</pays>
        <livres>
            <livreref idLivre="L14"/>
        </livres>
    </auteur>

    <!-- Histoire / Philosophie -->
    <auteur id="A14">
        <nom>Nicolas Machiavel</nom>
        <pays>Italie</pays>
        <livres>
            <livreref idLivre="L15"/>
        <livreref idLivre="L16"/></livres>
    </auteur>

    

    


</auteurs>
