=== baioumyhiba/Projet_bibliotheque/data/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Déclaration du type booléen simple -->
    <xs:simpleType name="booleanType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Déclaration du type pour auteurRef -->
    <xs:complexType name="auteurRefType">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Déclaration du type pour categorieRef -->
    <xs:complexType name="categorieRefType">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>


    <!-- Type livre -->
    <xs:complexType name="livreType">
        <xs:sequence>
            <xs:element name="titre" type="xs:string"/>
            <xs:element name="anneePublication" type="xs:integer"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="image" type="xs:string" minOccurs="0"/>
            <xs:element name="isbn" type="xs:string"/>
            <xs:element name="disponibilite" type="booleanType"/>
            <xs:element name="authors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="auteurRef" type="auteurRefType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="categories">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="categorieRef" type="categorieRefType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="idLivre" type="xs:ID" use="required"/>
    </xs:complexType>

    <!-- Élément racine -->
    <xs:element name="livres">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="livre" type="livreType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== baioumyhiba/Projet_bibliotheque/data/books.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="books.xsl"?><livres xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">

    <!-- üá´üá∑ Litt√©rature fran√ßaise -->
    

    <livre idLivre="L2">
        <titre>Notre-Dame de Paris</titre>
        <anneePublication>1831</anneePublication>
        <description>Notre-Dame de Paris est un roman de Victor Hugo, publi√© en 1831, qui se d√©roule √† Paris au XVe si√®cle, autour de la c√©l√®bre cath√©drale Notre-Dame. L‚Äôhistoire met en sc√®ne Quasimodo, le sonneur de cloches difforme et solitaire, Esmeralda, une jeune danseuse boh√©mienne, et Claude Frollo, l‚Äôarchidiacre tourment√©. √Ä travers leurs destins tragiques, le roman explore des th√®mes comme l‚Äôamour impossible, la fatalit√©, la diff√©rence et l‚Äôinjustice sociale. Victor Hugo utilise cette ≈ìuvre pour d√©noncer l‚Äôintol√©rance et la cruaut√© de la soci√©t√© envers ceux qui sont diff√©rents, tout en rendant hommage √† l‚Äôarchitecture gothique et au patrimoine de Paris.</description>
        <image>images/Notre-Dame-de-Paris.jpg</image>
        <isbn>9782070409196</isbn>
        <disponibilite>false</disponibilite>
        
        <categories>
            <categorieRef id="C1"/>
        </categories>
    <authors><auteurRef id="A5"/></authors></livre>

    <livre idLivre="L3">
        <titre>Madame Bovary</titre>
        <anneePublication>1857</anneePublication>
        <description>Madame Bovary est un roman de Gustave Flaubert, publi√© en 1857, qui raconte l‚Äôhistoire d‚ÄôEmma Bovary, une jeune femme mari√©e √† Charles Bovary, un m√©decin de campagne simple et ordinaire. R√™vant d‚Äôune vie passionn√©e et luxueuse, Emma s‚Äôennuie dans son mariage et cherche le bonheur √† travers des relations amoureuses et une vie de d√©penses excessives. Ses illusions romantiques la conduisent peu √† peu √† des dettes et √† une profonde d√©tresse. √Ä travers ce roman, Flaubert critique le romantisme excessif, l‚Äôennui de la vie provinciale et les illusions sociales, tout en montrant les cons√©quences tragiques du d√©calage entre les r√™ves et la r√©alit√©.</description>
         <image>images/3.jpg</image>
        <isbn>9782070413117</isbn>
        <disponibilite>true</disponibilite>
        <authors>
            <auteurRef id="A2"/>
        </authors>
        <categories>
            <categorieRef id="C1"/>
        </categories>
    </livre>

    <livre idLivre="L4">
        <titre>Le P√®re Goriot</titre>
        <anneePublication>1835</anneePublication>
        <description>Le P√®re Goriot est un roman de Honor√© de Balzac, publi√© en 1835, qui se d√©roule dans le Paris du XIX·µâ si√®cle. Il raconte l‚Äôhistoire de Goriot, un ancien commer√ßant ruin√© apr√®s avoir sacrifi√© toute sa fortune pour assurer le bonheur de ses deux filles, qui finissent par l‚Äôabandonner. Le roman suit aussi le parcours de Rastignac, un jeune √©tudiant ambitieux d√©couvrant la duret√© et l‚Äôhypocrisie de la soci√©t√© parisienne. √Ä travers cette ≈ìuvre, Balzac d√©nonce l‚Äô√©go√Øsme, l‚Äôambition sociale et la domination de l‚Äôargent, tout en montrant la trag√©die de l‚Äôamour paternel pouss√© √† l‚Äôextr√™me.</description>
        <image>images/4.jpg</image>
        <isbn>9782070419126</isbn>
        <disponibilite>true</disponibilite>
        <authors>
            <auteurRef id="A3"/>
        </authors>
        <categories>
            <categorieRef id="C1"/>
        </categories>
    </livre>

    <livre idLivre="L5">
        <titre>L‚Äô√âtranger</titre>
        <anneePublication>1942</anneePublication>
        <description>L‚Äô√âtranger est un roman de Albert Camus, publi√© en 1942, qui raconte l‚Äôhistoire de Meursault, un homme indiff√©rent aux normes sociales. Apr√®s la mort de sa m√®re, son absence d‚Äô√©motion choque son entourage. Plus tard, il commet un meurtre sans motivation claire et est jug√© davantage pour son comportement que pour son acte. √Ä travers ce personnage, Camus illustre la philosophie de l‚Äôabsurde, montrant le d√©calage entre l‚Äôhomme et le monde, ainsi que l‚Äôinjustice d‚Äôune soci√©t√© qui condamne ce qu‚Äôelle ne comprend pas.</description>
         <image>images/5.jpg</image>
        <isbn>9782070360022</isbn>
        <disponibilite>false</disponibilite>
        <authors>
            <auteurRef id="A4"/>
        </authors>
        <categories>
            <categorieRef id="C1"/>
        </categories>
    </livre>

    <!-- üá≤üá¶ Litt√©rature marocaine -->
    <livre idLivre="L6">
        <titre>La Bo√Æte √† merveilles</titre>
        <anneePublication>1954</anneePublication>
        <description>a Bo√Æte √† merveilles est un roman autobiographique de Ahmed Sefrioui, publi√© en 1954, qui raconte l'enfance de Sidi Mohammed, un jeune gar√ßon vivant dans la m√©dina de F√®s. √Ä travers son regard d'enfant, l'auteur d√©crit la vie quotidienne, les traditions, les f√™tes et les difficult√©s sociales du Maroc traditionnel. La ¬´ bo√Æte √† merveilles ¬ª est un objet symbolique dans lequel l'enfant conserve des souvenirs et des objets qui l'aident √† s'√©vader de la solitude et de la tristesse. L'≈ìuvre met en valeur la m√©moire, l'imagination et la culture marocaine, tout en √©voquant la pauvret√© et la condition humaine avec sensibilit√©.</description>
        <image>images/6.jpg</image>
        <isbn>9789954190197</isbn>
        <disponibilite>true</disponibilite>
        <authors>
            <auteurRef id="A5"/>
        </authors>
        <categories>
            <categorieRef id="C1"/>
            <categorieRef id="C6"/>
        </categories>
    </livre>

    <livre idLivre="L7">
        <titre>Le Pass√© simple</titre>
        <anneePublication>1954</anneePublication>
        <description>Le Pass√© simple est un roman autobiographique de Driss Chra√Øbi, publi√© en 1954, qui raconte la r√©volte d'un jeune gar√ßon contre l'autorit√© familiale et sociale. Le narrateur, appel√© Driss, grandit dans une famille marocaine traditionnelle domin√©e par un p√®re autoritaire et violent. √Ä travers son regard critique, le roman d√©nonce le patriarcat, l'oppression, l'hypocrisie sociale et certaines traditions rigides. Cette ≈ìuvre marque une rupture avec la litt√©rature marocaine classique et exprime un fort d√©sir de libert√©, de modernit√© et de remise en question des valeurs √©tablies.</description>
         <image>images/7.jpg</image>
        <isbn>9789954190203</isbn>
        <disponibilite>true</disponibilite>
        <authors>
            <auteurRef id="A6"/>
        </authors>
        <categories>
            <categorieRef id="C1"/>
            <categorieRef id="C6"/>
        </categories>
    </livre>

    <livre idLivre="L8">
        <titre>Il √©tait une fois un vieux couple heureux</titre>
        <anneePublication>2001</anneePublication>
        <description>Il √©tait une fois un vieux couple heureux est un roman de Mohammed Kha√Ør‚ÄëEddine, publi√© en 2002, qui raconte la vie simple et paisible d'un vieux couple vivant dans un village berb√®re du Maroc. Le mari, Boucha√Øb, consacre ses journ√©es √† √©crire un po√®me c√©l√©brant un saint, tandis que sa femme s'occupe du foyer et des traditions quotidiennes. √Ä travers leur quotidien, le roman c√©l√®bre la sagesse populaire, les coutumes amazighes et la r√©sistance culturelle face √† la modernit√©. Cette ≈ìuvre offre un regard po√©tique sur la vie rurale marocaine et souligne l'importance de la m√©moire, de la transmission et de l'harmonie avec la nature.</description>
         <image>images/8.jpg</image>
        <isbn>9789954190210</isbn>
        <disponibilite>false</disponibilite>
        <authors>
            <auteurRef id="A7"/>
        </authors>
        <categories>
            <categorieRef id="C1"/>
            <categorieRef id="C8"/>
        </categories>
    </livre>

    <livre idLivre="L9">
        <titre>Le Pain nu</titre>
        <anneePublication>1973</anneePublication>
        <description>Le Pain nu est un roman autobiographique de Mohammed Choukri, publi√© en 1973, qui raconte l'enfance et la jeunesse difficiles de l'auteur dans la ville de Tanger. Orphelin et pauvre, Mohammed Choukri grandit dans la mis√®re, confront√© √† la faim, √† la violence et √† l'errance. √Ä travers son r√©cit cru et sinc√®re, le roman d√©nonce les injustices sociales, la pauvret√© extr√™me et l'exclusion des plus vuln√©rables. Cette ≈ìuvre, marqu√©e par un r√©alisme brutal, exprime la lutte pour la survie et la qu√™te d'identit√© dans un environnement hostile, tout en offrant un t√©moignage poignant sur la condition humaine au Maroc du XX·µâ si√®cle.</description>
        <image>images/9.jpg</image>
        <isbn>9789954190227</isbn>
        <disponibilite>true</disponibilite>
        <authors>
            <auteurRef id="A8"/>
        </authors>
        <categories>
            <categorieRef id="C1"/>
            <categorieRef id="C6"/>
        </categories>
    </livre>

    <!-- üåç Litt√©rature mondiale -->
    <livre idLivre="L10">
        <titre>Don Quichotte</titre>
        <anneePublication>1605</anneePublication>
        <description>Don Quichotte est un roman de Miguel de Cervantes, publi√© en deux parties en 1605 et 1615, qui raconte les aventures de Don Quichotte, un noble espagnol obs√©d√© par les romans de chevalerie, et de son fid√®le √©cuyer Sancho Panza. D√©cidant de devenir chevalier errant, Don Quichotte parcourt la campagne pour d√©fendre la justice, combattre le mal et prot√©ger les opprim√©s, mais ses id√©aux le conduisent souvent √† des situations comiques ou absurdes. √Ä travers ce r√©cit, le roman critique les illusions et les exc√®s des id√©aux chevaleresques, tout en explorant les th√®mes de la folie, de la r√©alit√© versus l‚Äôillusion et de la condition humaine. Cette ≈ìuvre, m√™lant humour et r√©flexion philosophique, est consid√©r√©e comme l‚Äôun des fondements de la litt√©rature moderne.</description>
        <image>images/10.jpg</image>
