=== baioumyhiba/Projet_bibliotheque/data/categories.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Élément racine -->
    <xs:element name="categories">
        <xs:complexType>
            <xs:sequence>
                
                <!-- Plusieurs catégories -->
                <xs:element name="categorie" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="libelle" type="xs:string"/>
                        </xs:sequence>

                        <!-- Clé primaire -->
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== baioumyhiba/Projet_bibliotheque/data/categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="categories.xsl"?>

<categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="categories.xsd">

    <categorie id="C1">
        <libelle>Roman</libelle>
    </categorie>

    <categorie id="C2">
        <libelle>Histoire / Philosophie</libelle>
    </categorie>

    <categorie id="C3">
        <libelle>Science-Fiction</libelle>
    </categorie>

    <categorie id="C4">
        <libelle>Fantasy</libelle>
    </categorie>

    <categorie id="C5">
        <libelle>Thriller / Suspense</libelle>
    </categorie>

    <categorie id="C6">
        <libelle>Biographie</libelle>
    </categorie>

    <categorie id="C7">
        <libelle>Policier</libelle>
    </categorie>

    <categorie id="C8">
        <libelle>Poésie</libelle>
    </categorie>

    <categorie id="C9">
        <libelle>Développement personnel</libelle>
    </categorie>

    <categorie id="C10">
        <libelle>Informatique / Technologie</libelle>
    </categorie>

    <categorie id="C11">
        <libelle>Art / Culture</libelle>
    </categorie>

    <categorie id="C12">
        <libelle>Jeunesse</libelle>
    </categorie>

</categories>
